#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from todoapp import app as application

from todoflask import *

create_all()

u1 = auth.User(username='admin', admin=True, active=True)
u1.email = 'shekhargulati84@gmail.com'
u1.set_password('secret')
u1.save()

#add another user
u2 = auth.User(username='shekhargulati', admin=True, active=True)
u2.email = 'shekhargulati84@gmail.com'
u2.set_password('password')
u2.save()